
GET http://localhost:8082/users

#####
GET http://localhost:8082/users/search?gender=male&age=49

###
GET http://localhost:8082/blogs

###
POST http://localhost:8082/blogs/new
Content-Type:application/json

{
    "title":"Blog of goa",
    "authore":["Rishu", "Sonali"],
    "publishedAt":null
}